-keep class dagger.hilt.** { *; }
-keep class javax.inject.** { *; }
-keep class com.github.mjdev.libaums.** { *; }
-dontwarn com.github.mjdev.libaums.**
-keep class androidx.media3.exoplayer.** { *; }
-keepclassmembers class * extends androidx.media3.session.MediaSessionService { *; }
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile
